export const productImages = {
  '/images/agri/3M PVC PIPE ISI.png': require('../../assets/images/agri/3M PVC PIPE ISI.png'),
  '/images/agri/3M PVC PIPE.png': require('../../assets/images/agri/3M PVC PIPE.png'),
  '/images/agri/6M ECO PVC PIPE.png': require('../../assets/images/agri/6M ECO PVC PIPE.png'),
  '/images/agri/6M PVC PIPE ISI.png': require('../../assets/images/agri/6M PVC PIPE ISI.png'),
  '/images/agri/6M PVC PIPE.png': require('../../assets/images/agri/6M PVC PIPE.png'),
  '/images/agri/AGRICULTURE PVC PIPE (PLAIN SOCKET).png': require('../../assets/images/agri/AGRICULTURE PVC PIPE (PLAIN SOCKET).png'),
  '/images/agri/AGRICULTURE PVC PIPE (RING SOCKET).png': require('../../assets/images/agri/AGRICULTURE PVC PIPE (RING SOCKET).png'),
  '/images/agri/COUPLER (LW).png': require('../../assets/images/agri/COUPLER (LW).png'),
  '/images/agri/ELBOW 90 (LW).png': require('../../assets/images/agri/ELBOW 90 (LW).png'),
  '/images/agri/END CAP (LW).png': require('../../assets/images/agri/END CAP (LW).png'),
  '/images/agri/FABRICATED COUPLER (LW).png': require('../../assets/images/agri/FABRICATED COUPLER (LW).png'),
  '/images/agri/FABRICATED COUPLER 6KG (LW).png': require('../../assets/images/agri/FABRICATED COUPLER 6KG (LW).png'),
  '/images/agri/LAPETA (LDPE) AGRICULTURE PIPE.png': require('../../assets/images/agri/LAPETA (LDPE) AGRICULTURE PIPE.png'),
  '/images/agri/LONG BEND (LW).png': require('../../assets/images/agri/LONG BEND (LW).png'),
  '/images/agri/PN10 - COUPLER ISI.png': require('../../assets/images/agri/PN10 - COUPLER ISI.png'),
  '/images/agri/PN10 - ELBOW ISI.png': require('../../assets/images/agri/PN10 - ELBOW ISI.png'),
  '/images/agri/PN10 - END CAP ISI.png': require('../../assets/images/agri/PN10 - END CAP ISI.png'),
  '/images/agri/PN10 - FTA ISI.png': require('../../assets/images/agri/PN10 - FTA ISI.png'),
  '/images/agri/PN10 - MTA ISI.png': require('../../assets/images/agri/PN10 - MTA ISI.png'),
  '/images/agri/PN10 - REDUCING BUSH ISI.png': require('../../assets/images/agri/PN10 - REDUCING BUSH ISI.png'),
  '/images/agri/PN10 - TEE ISI.png': require('../../assets/images/agri/PN10 - TEE ISI.png'),
  '/images/agri/PN10 - UNION ISI.png': require('../../assets/images/agri/PN10 - UNION ISI.png'),
  '/images/agri/PN6 - BEND 45 ISI.png': require('../../assets/images/agri/PN6 - BEND 45 ISI.png'),
  '/images/agri/PN6 - COUPLER ISI.png': require('../../assets/images/agri/PN6 - COUPLER ISI.png'),
  '/images/agri/PN6 - ELBOW 90 ISI.png': require('../../assets/images/agri/PN6 - ELBOW 90 ISI.png'),
  '/images/agri/PN6 - END CAP (THREADED) ISI.png': require('../../assets/images/agri/PN6 - END CAP (THREADED) ISI.png'),
  '/images/agri/PN6 - END CAP ISI.png': require('../../assets/images/agri/PN6 - END CAP ISI.png'),
  '/images/agri/PN6 - FTA ISI.png': require('../../assets/images/agri/PN6 - FTA ISI.png'),
  '/images/agri/PN6 - MTA ISI.png': require('../../assets/images/agri/PN6 - MTA ISI.png'),
  '/images/agri/PN6 - REDUCING TEE ISI.png': require('../../assets/images/agri/PN6 - REDUCING TEE ISI.png'),
  '/images/agri/PN6 - SERVICE SADDLE ISI.png': require('../../assets/images/agri/PN6 - SERVICE SADDLE ISI.png'),
  '/images/agri/PN6 - TEE ISI.png': require('../../assets/images/agri/PN6 - TEE ISI.png'),
  '/images/agri/REDUCER (LW).png': require('../../assets/images/agri/REDUCER (LW).png'),
  '/images/agri/REDUCING BUSH (LW).png': require('../../assets/images/agri/REDUCING BUSH (LW).png'),
  '/images/agri/TEE (LW).png': require('../../assets/images/agri/TEE (LW).png'),
  '/images/casing/3M CASING PIPE (THREADED).png': require('../../assets/images/casing/3M CASING PIPE (THREADED).png'),
  '/images/casing/3M CASING PIPE.png': require('../../assets/images/casing/3M CASING PIPE.png'),
  '/images/column/3M ECO - V4 PIPE.png': require('../../assets/images/column/3M ECO - V4 PIPE.png'),
  '/images/column/3M HEAVY PIPE.png': require('../../assets/images/column/3M HEAVY PIPE.png'),
  '/images/column/3M MEDIUM PIPE.png': require('../../assets/images/column/3M MEDIUM PIPE.png'),
  '/images/column/3M MEDIUM PLUS PIPE.png': require('../../assets/images/column/3M MEDIUM PLUS PIPE.png'),
  '/images/column/3M STANDARD PIPE.png': require('../../assets/images/column/3M STANDARD PIPE.png'),
  '/images/column/3M STANDARD PLUS PIPE.png': require('../../assets/images/column/3M STANDARD PLUS PIPE.png'),
  '/images/cpvc/CPVC - 3 In 1 Mixer Adaptor 6.png': require('../../assets/images/cpvc/CPVC - 3 In 1 Mixer Adaptor 6.png'),
  '/images/cpvc/CPVC - 3 In 1 Mixer Frame 6.png': require('../../assets/images/cpvc/CPVC - 3 In 1 Mixer Frame 6.png'),
  '/images/cpvc/CPVC - Ball Valve.png': require('../../assets/images/cpvc/CPVC - Ball Valve.png'),
  '/images/cpvc/CPVC - Bend 45.png': require('../../assets/images/cpvc/CPVC - Bend 45.png'),
  '/images/cpvc/CPVC - Brass FTA.png': require('../../assets/images/cpvc/CPVC - Brass FTA.png'),
  '/images/cpvc/CPVC - Brass MTA.png': require('../../assets/images/cpvc/CPVC - Brass MTA.png'),
  '/images/cpvc/CPVC - Brass Tee.png': require('../../assets/images/cpvc/CPVC - Brass Tee.png'),
  '/images/cpvc/CPVC - Concealed Valve (Full Turn).png': require('../../assets/images/cpvc/CPVC - Concealed Valve (Full Turn).png'),
  '/images/cpvc/CPVC - Concealed Valve (Quarter Turn).png': require('../../assets/images/cpvc/CPVC - Concealed Valve (Quarter Turn).png'),
  '/images/cpvc/CPVC - Coupler.png': require('../../assets/images/cpvc/CPVC - Coupler.png'),
  '/images/cpvc/CPVC - Cross Tee.png': require('../../assets/images/cpvc/CPVC - Cross Tee.png'),
  '/images/cpvc/CPVC - Elbow 90.png': require('../../assets/images/cpvc/CPVC - Elbow 90.png'),
  '/images/cpvc/CPVC - End Cap.png': require('../../assets/images/cpvc/CPVC - End Cap.png'),
  '/images/cpvc/CPVC - End Plug.png': require('../../assets/images/cpvc/CPVC - End Plug.png'),
  '/images/cpvc/CPVC - FTA.png': require('../../assets/images/cpvc/CPVC - FTA.png'),
  '/images/cpvc/CPVC - Metal Clamp.png': require('../../assets/images/cpvc/CPVC - Metal Clamp.png'),
  '/images/cpvc/CPVC - MTA.png': require('../../assets/images/cpvc/CPVC - MTA.png'),
  '/images/cpvc/CPVC - Nail Clamp.png': require('../../assets/images/cpvc/CPVC - Nail Clamp.png'),
  '/images/cpvc/CPVC - NRV.png': require('../../assets/images/cpvc/CPVC - NRV.png'),
  '/images/cpvc/CPVC - Reducing Brass FTA.png': require('../../assets/images/cpvc/CPVC - Reducing Brass FTA.png'),
  '/images/cpvc/CPVC - Reducing Brass MTA.png': require('../../assets/images/cpvc/CPVC - Reducing Brass MTA.png'),
  '/images/cpvc/CPVC - Reducing Brass Tee.png': require('../../assets/images/cpvc/CPVC - Reducing Brass Tee.png'),
  '/images/cpvc/CPVC - Reducing Bush.png': require('../../assets/images/cpvc/CPVC - Reducing Bush.png'),
  '/images/cpvc/CPVC - Reducing Coupler.png': require('../../assets/images/cpvc/CPVC - Reducing Coupler.png'),
  '/images/cpvc/CPVC - Reducing Elbow 90.png': require('../../assets/images/cpvc/CPVC - Reducing Elbow 90.png'),
  '/images/cpvc/CPVC - Reducing FTA Hexa Brass.png': require('../../assets/images/cpvc/CPVC - Reducing FTA Hexa Brass.png'),
  '/images/cpvc/CPVC - Reducing MTA Hexa Brass.png': require('../../assets/images/cpvc/CPVC - Reducing MTA Hexa Brass.png'),
  '/images/cpvc/CPVC - Reducing Tee.png': require('../../assets/images/cpvc/CPVC - Reducing Tee.png'),
  '/images/cpvc/CPVC - SCH-40 Pipe.png': require('../../assets/images/cpvc/CPVC - SCH-40 Pipe.png'),
  '/images/cpvc/CPVC - SCH-80 Pipe.png': require('../../assets/images/cpvc/CPVC - SCH-80 Pipe.png'),
  '/images/cpvc/CPVC - SDR-11 Pipe ISI.png': require('../../assets/images/cpvc/CPVC - SDR-11 Pipe ISI.png'),
  '/images/cpvc/CPVC - SDR-13.5 Pipe ISI.png': require('../../assets/images/cpvc/CPVC - SDR-13.5 Pipe ISI.png'),
  '/images/cpvc/CPVC - Step Over Bend (Moulded).png': require('../../assets/images/cpvc/CPVC - Step Over Bend (Moulded).png'),
  '/images/cpvc/CPVC - Step Over Bend.png': require('../../assets/images/cpvc/CPVC - Step Over Bend.png'),
  '/images/cpvc/CPVC - Tank Nipple (Socketed).png': require('../../assets/images/cpvc/CPVC - Tank Nipple (Socketed).png'),
  '/images/cpvc/CPVC - Tank Nipple (Threaded).png': require('../../assets/images/cpvc/CPVC - Tank Nipple (Threaded).png'),
  '/images/cpvc/CPVC - Tee.png': require('../../assets/images/cpvc/CPVC - Tee.png'),
  '/images/cpvc/CPVC - Transition Bush.png': require('../../assets/images/cpvc/CPVC - Transition Bush.png'),
  '/images/cpvc/CPVC - Union.png': require('../../assets/images/cpvc/CPVC - Union.png'),
  '/images/drip/12MM FLAT EMITTING PIPE.png': require('../../assets/images/drip/12MM FLAT EMITTING PIPE.png'),
  '/images/drip/12MM FLAT INLINE PIPE ISI.png': require('../../assets/images/drip/12MM FLAT INLINE PIPE ISI.png'),
  '/images/drip/12MM PLAIN LATERAL ONLINE PIPE.png': require('../../assets/images/drip/12MM PLAIN LATERAL ONLINE PIPE.png'),
  '/images/drip/12MM ROUND INLINE PIPE ISI.png': require('../../assets/images/drip/12MM ROUND INLINE PIPE ISI.png'),
  '/images/drip/16MM FLAT EMITTING PIPE.png': require('../../assets/images/drip/16MM FLAT EMITTING PIPE.png'),
  '/images/drip/16MM FLAT INLINE PIPE ISI.png': require('../../assets/images/drip/16MM FLAT INLINE PIPE ISI.png'),
  '/images/drip/16MM PLAIN LATERAL ONLINE PIPE.png': require('../../assets/images/drip/16MM PLAIN LATERAL ONLINE PIPE.png'),
  '/images/drip/16MM ROUND INLINE PIPE ISI.png': require('../../assets/images/drip/16MM ROUND INLINE PIPE ISI.png'),
  '/images/drip/20MM FLAT EMITTING PIPE.png': require('../../assets/images/drip/20MM FLAT EMITTING PIPE.png'),
  '/images/drip/20MM FLAT INLINE PIPE ISI.png': require('../../assets/images/drip/20MM FLAT INLINE PIPE ISI.png'),
  '/images/drip/20MM PLAIN LATERAL ONLINE PIPE.png': require('../../assets/images/drip/20MM PLAIN LATERAL ONLINE PIPE.png'),
  '/images/drip/20MM ROUND INLINE PIPE ISI.png': require('../../assets/images/drip/20MM ROUND INLINE PIPE ISI.png'),
  '/images/drip/32MM PLAIN LATERAL ONLINE PIPE.png': require('../../assets/images/drip/32MM PLAIN LATERAL ONLINE PIPE.png'),
  '/images/eco_drainage/ECO DRAINAGE DOWNSPOUT PIPE.png': require('../../assets/images/eco_drainage/ECO DRAINAGE DOWNSPOUT PIPE.png'),
  '/images/eco_drainage/ECO DRAINAGE SWR PIPE.png': require('../../assets/images/eco_drainage/ECO DRAINAGE SWR PIPE.png'),
  '/images/eco_drainage/RINGFIT PIPE.png': require('../../assets/images/eco_drainage/RINGFIT PIPE.png'),
  '/images/eco_drainage/SELFIT PIPE.png': require('../../assets/images/eco_drainage/SELFIT PIPE.png'),
  '/images/faucets/EDGE SERIES 2 WAY BIB TAB.png': require('../../assets/images/faucets/EDGE SERIES 2 WAY BIB TAB.png'),
  '/images/faucets/EDGE SERIES ANGULAR VALVE.png': require('../../assets/images/faucets/EDGE SERIES ANGULAR VALVE.png'),
  '/images/faucets/EDGE SERIES LONG BODY TAP.png': require('../../assets/images/faucets/EDGE SERIES LONG BODY TAP.png'),
  '/images/faucets/EDGE SERIES PILLAR TAP.png': require('../../assets/images/faucets/EDGE SERIES PILLAR TAP.png'),
  '/images/faucets/EDGE SERIES SHORT BODY TAP.png': require('../../assets/images/faucets/EDGE SERIES SHORT BODY TAP.png'),
  '/images/faucets/EDGE SERIES SINK TAP.png': require('../../assets/images/faucets/EDGE SERIES SINK TAP.png'),
  '/images/faucets/EDGE SERIES SWAN NECK.png': require('../../assets/images/faucets/EDGE SERIES SWAN NECK.png'),
  '/images/faucets/REGULAR SERIES 2 WAY ANGULAR VALVE.png': require('../../assets/images/faucets/REGULAR SERIES 2 WAY ANGULAR VALVE.png'),
  '/images/faucets/REGULAR SERIES 2 WAY BIB TAP.png': require('../../assets/images/faucets/REGULAR SERIES 2 WAY BIB TAP.png'),
  '/images/faucets/REGULAR SERIES ANGULAR VALVE.png': require('../../assets/images/faucets/REGULAR SERIES ANGULAR VALVE.png'),
  '/images/faucets/REGULAR SERIES LONG BODY BIB TAP.png': require('../../assets/images/faucets/REGULAR SERIES LONG BODY BIB TAP.png'),
  '/images/faucets/REGULAR SERIES PILLAR TAP.png': require('../../assets/images/faucets/REGULAR SERIES PILLAR TAP.png'),
  '/images/faucets/REGULAR SERIES SHORT BODY BIB TAP.png': require('../../assets/images/faucets/REGULAR SERIES SHORT BODY BIB TAP.png'),
  '/images/faucets/REGULAR SERIES SINK TAP.png': require('../../assets/images/faucets/REGULAR SERIES SINK TAP.png'),
  '/images/faucets/REGULAR SERIES SWAN NECK.png': require('../../assets/images/faucets/REGULAR SERIES SWAN NECK.png'),
  '/images/faucets/SMART SERIES 2 WAY ANGULAR VALVE.png': require('../../assets/images/faucets/SMART SERIES 2 WAY ANGULAR VALVE.png'),
  '/images/faucets/SMART SERIES 2 WAY BIB TAP.png': require('../../assets/images/faucets/SMART SERIES 2 WAY BIB TAP.png'),
  '/images/faucets/SMART SERIES ANGULAR VALVE.png': require('../../assets/images/faucets/SMART SERIES ANGULAR VALVE.png'),
  '/images/faucets/SMART SERIES LONG BODY BIB TAP.png': require('../../assets/images/faucets/SMART SERIES LONG BODY BIB TAP.png'),
  '/images/faucets/SMART SERIES PILLAR TAP.png': require('../../assets/images/faucets/SMART SERIES PILLAR TAP.png'),
  '/images/faucets/SMART SERIES SHORT BODY BIB TAP.png': require('../../assets/images/faucets/SMART SERIES SHORT BODY BIB TAP.png'),
  '/images/faucets/SMART SERIES SINK TAP.png': require('../../assets/images/faucets/SMART SERIES SINK TAP.png'),
  '/images/faucets/SMART SERIES SWAN NECK.png': require('../../assets/images/faucets/SMART SERIES SWAN NECK.png'),
  '/images/garden/BRAIDED PIPE.png': require('../../assets/images/garden/BRAIDED PIPE.png'),
  '/images/garden/FOAM PIPE.png': require('../../assets/images/garden/FOAM PIPE.png'),
  '/images/garden/LEVEL PIPE.png': require('../../assets/images/garden/LEVEL PIPE.png'),
  '/images/garden/ORA FLOW - BRAIDED PIPE.png': require('../../assets/images/garden/ORA FLOW - BRAIDED PIPE.png'),
  '/images/garden/ORA FLOW - HEAVY DUTY PIPE.png': require('../../assets/images/garden/ORA FLOW - HEAVY DUTY PIPE.png'),
  '/images/garden/SUPER FLOW PIPE (MILKY & TRANSPARENT).png': require('../../assets/images/garden/SUPER FLOW PIPE (MILKY & TRANSPARENT).png'),
  '/images/hdpe/HDPE END CAP.png': require('../../assets/images/hdpe/HDPE END CAP.png'),
  '/images/hdpe/MDPE PIPE.png': require('../../assets/images/hdpe/MDPE PIPE.png'),
  '/images/hdpe/PE-100 OD PIPE ISI.png': require('../../assets/images/hdpe/PE-100 OD PIPE ISI.png'),
  '/images/hdpe/PE-63 ID PIPE.png': require('../../assets/images/hdpe/PE-63 ID PIPE.png'),
  '/images/hdpe/PE-63 OD PIPE ISI.png': require('../../assets/images/hdpe/PE-63 OD PIPE ISI.png'),
  '/images/hdpe/PE-80 OD PIPE ISI.png': require('../../assets/images/hdpe/PE-80 OD PIPE ISI.png'),
  '/images/household/CONSTRUCTION GHAMELA SHIVA.png': require('../../assets/images/household/CONSTRUCTION GHAMELA SHIVA.png'),
  '/images/household/ECO DELTA GHAMELA KRISHNA.png': require('../../assets/images/household/ECO DELTA GHAMELA KRISHNA.png'),
  '/images/household/ECO DELTA GHAMELA TEJASWI.png': require('../../assets/images/household/ECO DELTA GHAMELA TEJASWI.png'),
  '/images/household/MULTIPURPOSE GHAMELA ANIKET.png': require('../../assets/images/household/MULTIPURPOSE GHAMELA ANIKET.png'),
  '/images/household/MULTIPURPOSE GHAMELA GAJRAJ.png': require('../../assets/images/household/MULTIPURPOSE GHAMELA GAJRAJ.png'),
  '/images/household/MULTIPURPOSE GHAMELA GOURI.png': require('../../assets/images/household/MULTIPURPOSE GHAMELA GOURI.png'),
  '/images/household/MULTIPURPOSE GHAMELA KRISHNA.png': require('../../assets/images/household/MULTIPURPOSE GHAMELA KRISHNA.png'),
  '/images/household/MULTIPURPOSE GHAMELA RAGHAV.png': require('../../assets/images/household/MULTIPURPOSE GHAMELA RAGHAV.png'),
  '/images/household/MULTIPURPOSE GHAMELA TEJASWI.png': require('../../assets/images/household/MULTIPURPOSE GHAMELA TEJASWI.png'),
  '/images/sanitary/CENTER SINGLE PUSH FLUSH 8L.png': require('../../assets/images/sanitary/CENTER SINGLE PUSH FLUSH 8L.png'),
  '/images/sanitary/DUAL FLUSH 10L.png': require('../../assets/images/sanitary/DUAL FLUSH 10L.png'),
  '/images/sanitary/DUAL FLUSH DUAL COLOUR (ECONOMY 10L).png': require('../../assets/images/sanitary/DUAL FLUSH DUAL COLOUR (ECONOMY 10L).png'),
  '/images/sanitary/DUAL FLUSH DUAL COLOUR (PREMIUM 10L).png': require('../../assets/images/sanitary/DUAL FLUSH DUAL COLOUR (PREMIUM 10L).png'),
  '/images/sanitary/EWC SEAT COVER (WITH JET).png': require('../../assets/images/sanitary/EWC SEAT COVER (WITH JET).png'),
  '/images/sanitary/EWC SEAT COVER (WITHOUT JET).png': require('../../assets/images/sanitary/EWC SEAT COVER (WITHOUT JET).png'),
  '/images/sanitary/SINGLE SIDE HANDLE FLUSH 8L.png': require('../../assets/images/sanitary/SINGLE SIDE HANDLE FLUSH 8L.png'),
  '/images/solvent/CPVC SOLVENT CEMENT (PLASTIC BOTTLE).png': require('../../assets/images/solvent/CPVC SOLVENT CEMENT (PLASTIC BOTTLE).png'),
  '/images/solvent/CPVC SOLVENT CEMENT (TIN).png': require('../../assets/images/solvent/CPVC SOLVENT CEMENT (TIN).png'),
  '/images/solvent/CPVC SOLVENT CEMENT (TUBE).png': require('../../assets/images/solvent/CPVC SOLVENT CEMENT (TUBE).png'),
  '/images/solvent/ECO - PVC SOLVENT CEMENT (PLASTIC BOTTLE).png': require('../../assets/images/solvent/ECO - PVC SOLVENT CEMENT (PLASTIC BOTTLE).png'),
  '/images/solvent/PVC SOLVENT CEMENT (PLASTIC BOTTLE).png': require('../../assets/images/solvent/PVC SOLVENT CEMENT (PLASTIC BOTTLE).png'),
  '/images/solvent/RUBBER LUBRICANT (PLASTIC BOTTLE).png': require('../../assets/images/solvent/RUBBER LUBRICANT (PLASTIC BOTTLE).png'),
  '/images/solvent/UPVC SOLVENT CEMENT (PLASTIC BOTTLE).png': require('../../assets/images/solvent/UPVC SOLVENT CEMENT (PLASTIC BOTTLE).png'),
  '/images/solvent/UPVC SOLVENT CEMENT (TIN).png': require('../../assets/images/solvent/UPVC SOLVENT CEMENT (TIN).png'),
  '/images/solvent/UPVC SOLVENT CEMENT (TUBE).png': require('../../assets/images/solvent/UPVC SOLVENT CEMENT (TUBE).png'),
  '/images/sprinkler/30 NOS SPRINKLER SET ISI.png': require('../../assets/images/sprinkler/30 NOS SPRINKLER SET ISI.png'),
  '/images/sprinkler/30 NOS SPRINKLER SET.png': require('../../assets/images/sprinkler/30 NOS SPRINKLER SET.png'),
  '/images/sprinkler/6M SPRINKLER PIPE ISI.png': require('../../assets/images/sprinkler/6M SPRINKLER PIPE ISI.png'),
  '/images/sprinkler/6M SPRINKLER PIPE.png': require('../../assets/images/sprinkler/6M SPRINKLER PIPE.png'),
  '/images/sprinkler/FOOT BOTTOM ADAPTOR ISI.png': require('../../assets/images/sprinkler/FOOT BOTTOM ADAPTOR ISI.png'),
  '/images/sprinkler/GI RISER PIPE ISI.png': require('../../assets/images/sprinkler/GI RISER PIPE ISI.png'),
  '/images/sprinkler/LATCH & CLAMP ISI.png': require('../../assets/images/sprinkler/LATCH & CLAMP ISI.png'),
  '/images/sprinkler/NOZZEL GUN (METAL) ISI.png': require('../../assets/images/sprinkler/NOZZEL GUN (METAL) ISI.png'),
  '/images/sprinkler/PUMP CONNECTING NIPPLE (PCN) ISI.png': require('../../assets/images/sprinkler/PUMP CONNECTING NIPPLE (PCN) ISI.png'),
  '/images/sprinkler/SPRINKLER BEND ISI.png': require('../../assets/images/sprinkler/SPRINKLER BEND ISI.png'),
  '/images/sprinkler/SPRINKLER END CAP ISI.png': require('../../assets/images/sprinkler/SPRINKLER END CAP ISI.png'),
  '/images/sprinkler/SPRINKLER TEE ISI.png': require('../../assets/images/sprinkler/SPRINKLER TEE ISI.png'),
  '/images/swr/JALI.png': require('../../assets/images/swr/JALI.png'),
  '/images/swr/MULTI FLOW TRAP (WITH JALI).png': require('../../assets/images/swr/MULTI FLOW TRAP (WITH JALI).png'),
  '/images/swr/MULTI FLOW TRAP (WITHOUT JALI).png': require('../../assets/images/swr/MULTI FLOW TRAP (WITHOUT JALI).png'),
  '/images/swr/NAHANI TRAP (WITH JALI).png': require('../../assets/images/swr/NAHANI TRAP (WITH JALI).png'),
  '/images/swr/NAHANI TRAP (WITHOUT JALI).png': require('../../assets/images/swr/NAHANI TRAP (WITHOUT JALI).png'),
  '/images/swr/P TRAP.png': require('../../assets/images/swr/P TRAP.png'),
  '/images/swr/PIPE CLIP.png': require('../../assets/images/swr/PIPE CLIP.png'),
  '/images/swr/SWR RINGFIT - BEND 45 ISI.png': require('../../assets/images/swr/SWR RINGFIT - BEND 45 ISI.png'),
  '/images/swr/SWR RINGFIT - BEND 45.png': require('../../assets/images/swr/SWR RINGFIT - BEND 45.png'),
  '/images/swr/SWR RINGFIT - BEND 87.5 ISI.png': require('../../assets/images/swr/SWR RINGFIT - BEND 87.5 ISI.png'),
  '/images/swr/SWR RINGFIT - BEND 87.5.png': require('../../assets/images/swr/SWR RINGFIT - BEND 87.5.png'),
  '/images/swr/SWR RINGFIT - CLEANING PIPES.png': require('../../assets/images/swr/SWR RINGFIT - CLEANING PIPES.png'),
  '/images/swr/SWR RINGFIT - COUPLER ISI.png': require('../../assets/images/swr/SWR RINGFIT - COUPLER ISI.png'),
  '/images/swr/SWR RINGFIT - COUPLER.png': require('../../assets/images/swr/SWR RINGFIT - COUPLER.png'),
  '/images/swr/SWR RINGFIT - DOOR BEND 87.5 ISI.png': require('../../assets/images/swr/SWR RINGFIT - DOOR BEND 87.5 ISI.png'),
  '/images/swr/SWR RINGFIT - DOOR BEND 87.5.png': require('../../assets/images/swr/SWR RINGFIT - DOOR BEND 87.5.png'),
  '/images/swr/SWR RINGFIT - DOOR REDUCING TEE.png': require('../../assets/images/swr/SWR RINGFIT - DOOR REDUCING TEE.png'),
  '/images/swr/SWR RINGFIT - DOOR TEE ISI.png': require('../../assets/images/swr/SWR RINGFIT - DOOR TEE ISI.png'),
  '/images/swr/SWR RINGFIT - DOOR TEE.png': require('../../assets/images/swr/SWR RINGFIT - DOOR TEE.png'),
  '/images/swr/SWR RINGFIT - DOOR Y ISI.png': require('../../assets/images/swr/SWR RINGFIT - DOOR Y ISI.png'),
  '/images/swr/SWR RINGFIT - DOUBLE TEE.png': require('../../assets/images/swr/SWR RINGFIT - DOUBLE TEE.png'),
  '/images/swr/SWR RINGFIT - REDUCER ISI.png': require('../../assets/images/swr/SWR RINGFIT - REDUCER ISI.png'),
  '/images/swr/SWR RINGFIT - REDUCER.png': require('../../assets/images/swr/SWR RINGFIT - REDUCER.png'),
  '/images/swr/SWR RINGFIT - REDUCING TEE ISI.png': require('../../assets/images/swr/SWR RINGFIT - REDUCING TEE ISI.png'),
  '/images/swr/SWR RINGFIT - REDUCING TEE.png': require('../../assets/images/swr/SWR RINGFIT - REDUCING TEE.png'),
  '/images/swr/SWR RINGFIT - RINGFIT (DOUBLE SOCKET) PIPE.png': require('../../assets/images/swr/SWR RINGFIT - RINGFIT (DOUBLE SOCKET) PIPE.png'),
  '/images/swr/SWR RINGFIT - RINGFIT PIPE ISI.png': require('../../assets/images/swr/SWR RINGFIT - RINGFIT PIPE ISI.png'),
  '/images/swr/SWR RINGFIT - RINGFIT PIPE.png': require('../../assets/images/swr/SWR RINGFIT - RINGFIT PIPE.png'),
  '/images/swr/SWR RINGFIT - SINGLE TEE ISI.png': require('../../assets/images/swr/SWR RINGFIT - SINGLE TEE ISI.png'),
  '/images/swr/SWR RINGFIT - SINGLE TEE.png': require('../../assets/images/swr/SWR RINGFIT - SINGLE TEE.png'),
  '/images/swr/SWR RINGFIT - SINGLE Y ISI.png': require('../../assets/images/swr/SWR RINGFIT - SINGLE Y ISI.png'),
  '/images/swr/SWR SELFIT - BEND 45 ISI.png': require('../../assets/images/swr/SWR SELFIT - BEND 45 ISI.png'),
  '/images/swr/SWR SELFIT - BEND 45.png': require('../../assets/images/swr/SWR SELFIT - BEND 45.png'),
  '/images/swr/SWR SELFIT - BEND 87.5 ISI.png': require('../../assets/images/swr/SWR SELFIT - BEND 87.5 ISI.png'),
  '/images/swr/SWR SELFIT - BEND 87.5.png': require('../../assets/images/swr/SWR SELFIT - BEND 87.5.png'),
  '/images/swr/SWR SELFIT - CLEANING PIPE.png': require('../../assets/images/swr/SWR SELFIT - CLEANING PIPE.png'),
  '/images/swr/SWR SELFIT - COUPLER ISI.png': require('../../assets/images/swr/SWR SELFIT - COUPLER ISI.png'),
  '/images/swr/SWR SELFIT - COUPLER.png': require('../../assets/images/swr/SWR SELFIT - COUPLER.png'),
  '/images/swr/SWR SELFIT - DOOR BEND 87.5 ISI.png': require('../../assets/images/swr/SWR SELFIT - DOOR BEND 87.5 ISI.png'),
  '/images/swr/SWR SELFIT - DOOR BEND 87.5.png': require('../../assets/images/swr/SWR SELFIT - DOOR BEND 87.5.png'),
  '/images/swr/SWR SELFIT - DOOR TEE ISI.png': require('../../assets/images/swr/SWR SELFIT - DOOR TEE ISI.png'),
  '/images/swr/SWR SELFIT - DOOR TEE.png': require('../../assets/images/swr/SWR SELFIT - DOOR TEE.png'),
  '/images/swr/SWR SELFIT - DOOR Y ISI.png': require('../../assets/images/swr/SWR SELFIT - DOOR Y ISI.png'),
  '/images/swr/SWR SELFIT - REDUCER ISI.png': require('../../assets/images/swr/SWR SELFIT - REDUCER ISI.png'),
  '/images/swr/SWR SELFIT - REDUCER.png': require('../../assets/images/swr/SWR SELFIT - REDUCER.png'),
  '/images/swr/SWR SELFIT - REDUCING TEE ISI.png': require('../../assets/images/swr/SWR SELFIT - REDUCING TEE ISI.png'),
  '/images/swr/SWR SELFIT - REDUCING TEE.png': require('../../assets/images/swr/SWR SELFIT - REDUCING TEE.png'),
  '/images/swr/SWR SELFIT - SELFIT PIPES ISI.png': require('../../assets/images/swr/SWR SELFIT - SELFIT PIPES ISI.png'),
  '/images/swr/SWR SELFIT - SELFIT PIPES.png': require('../../assets/images/swr/SWR SELFIT - SELFIT PIPES.png'),
  '/images/swr/SWR SELFIT - SINGLE TEE ISI.png': require('../../assets/images/swr/SWR SELFIT - SINGLE TEE ISI.png'),
  '/images/swr/SWR SELFIT - SINGLE TEE.png': require('../../assets/images/swr/SWR SELFIT - SINGLE TEE.png'),
  '/images/swr/SWR SELFIT - SINGLE Y ISI.png': require('../../assets/images/swr/SWR SELFIT - SINGLE Y ISI.png'),
  '/images/swr/VENT COWL.png': require('../../assets/images/swr/VENT COWL.png'),
  '/images/tanks/Blow 10 Layer Gold.png': require('../../assets/images/tanks/Blow 10 Layer Gold.png'),
  '/images/tanks/Blow 10 Layer Ora.png': require('../../assets/images/tanks/Blow 10 Layer Ora.png'),
  '/images/tanks/Blow 2 Layer Black.png': require('../../assets/images/tanks/Blow 2 Layer Black.png'),
  '/images/tanks/Blow 6 Layer Gold.png': require('../../assets/images/tanks/Blow 6 Layer Gold.png'),
  '/images/tanks/Blow 6 Layer Green.png': require('../../assets/images/tanks/Blow 6 Layer Green.png'),
  '/images/tanks/Blow 6 Layer Ora.png': require('../../assets/images/tanks/Blow 6 Layer Ora.png'),
  '/images/tanks/Blow 6 Layer White.png': require('../../assets/images/tanks/Blow 6 Layer White.png'),
  '/images/tanks/Loft Tank Black.png': require('../../assets/images/tanks/Loft Tank Black.png'),
  '/images/tanks/Loft Tank White.png': require('../../assets/images/tanks/Loft Tank White.png'),
  '/images/tanks/LOFT WATER TANKS.png': require('../../assets/images/tanks/LOFT WATER TANKS.png'),
  '/images/tanks/Roto 10 Layer T3 Ora.png': require('../../assets/images/tanks/Roto 10 Layer T3 Ora.png'),
  '/images/tanks/Roto 2 Layer Black.png': require('../../assets/images/tanks/Roto 2 Layer Black.png'),
  '/images/tanks/Roto 2 Layer ISI Black.png': require('../../assets/images/tanks/Roto 2 Layer ISI Black.png'),
  '/images/tanks/Roto 3 Layer White.png': require('../../assets/images/tanks/Roto 3 Layer White.png'),
  '/images/tanks/Roto 4 Layer Double Puff Marble.png': require('../../assets/images/tanks/Roto 4 Layer Double Puff Marble.png'),
  '/images/tanks/Roto 4 Layer Double Puff White.png': require('../../assets/images/tanks/Roto 4 Layer Double Puff White.png'),
  '/images/tanks/Roto 6 Layer Double Puff Marble.png': require('../../assets/images/tanks/Roto 6 Layer Double Puff Marble.png'),
  '/images/tanks/Roto 6 Layer Double Puff White.png': require('../../assets/images/tanks/Roto 6 Layer Double Puff White.png'),
  '/images/tanks/Underground Tank Black.png': require('../../assets/images/tanks/Underground Tank Black.png'),
  '/images/upvc/UPVC- BALL VALVE (LONG HANDLE).png': require('../../assets/images/upvc/UPVC- BALL VALVE (LONG HANDLE).png'),
  '/images/upvc/UPVC- BALL VALVE (SHORT HANDLE).png': require('../../assets/images/upvc/UPVC- BALL VALVE (SHORT HANDLE).png'),
  '/images/upvc/UPVC- BEND 45.png': require('../../assets/images/upvc/UPVC- BEND 45.png'),
  '/images/upvc/UPVC- BRASS ELBOW 90.png': require('../../assets/images/upvc/UPVC- BRASS ELBOW 90.png'),
  '/images/upvc/UPVC- BRASS FTA.png': require('../../assets/images/upvc/UPVC- BRASS FTA.png'),
  '/images/upvc/UPVC- BRASS MTA.png': require('../../assets/images/upvc/UPVC- BRASS MTA.png'),
  '/images/upvc/UPVC- BRASS TEE.png': require('../../assets/images/upvc/UPVC- BRASS TEE.png'),
  '/images/upvc/UPVC- CONCEALED VALVE (FULL TURN).png': require('../../assets/images/upvc/UPVC- CONCEALED VALVE (FULL TURN).png'),
  '/images/upvc/UPVC- COUPLER.png': require('../../assets/images/upvc/UPVC- COUPLER.png'),
  '/images/upvc/UPVC- CROSS TEE.png': require('../../assets/images/upvc/UPVC- CROSS TEE.png'),
  '/images/upvc/UPVC- ELBOW 90.png': require('../../assets/images/upvc/UPVC- ELBOW 90.png'),
  '/images/upvc/UPVC- END CAP.png': require('../../assets/images/upvc/UPVC- END CAP.png'),
  '/images/upvc/UPVC- END PLUG.png': require('../../assets/images/upvc/UPVC- END PLUG.png'),
  '/images/upvc/UPVC- FTA.png': require('../../assets/images/upvc/UPVC- FTA.png'),
  '/images/upvc/UPVC- METAL CLAMP.png': require('../../assets/images/upvc/UPVC- METAL CLAMP.png'),
  '/images/upvc/UPVC- MTA.png': require('../../assets/images/upvc/UPVC- MTA.png'),
  '/images/upvc/UPVC- NAIL CLAMP.png': require('../../assets/images/upvc/UPVC- NAIL CLAMP.png'),
  '/images/upvc/UPVC- NRV.png': require('../../assets/images/upvc/UPVC- NRV.png'),
  '/images/upvc/UPVC- REDUCING BRASS ELBOW 90.png': require('../../assets/images/upvc/UPVC- REDUCING BRASS ELBOW 90.png'),
  '/images/upvc/UPVC- REDUCING BRASS TEE.png': require('../../assets/images/upvc/UPVC- REDUCING BRASS TEE.png'),
  '/images/upvc/UPVC- REDUCING BUSH.png': require('../../assets/images/upvc/UPVC- REDUCING BUSH.png'),
  '/images/upvc/UPVC- REDUCING COUPLER.png': require('../../assets/images/upvc/UPVC- REDUCING COUPLER.png'),
  '/images/upvc/UPVC- REDUCING ELBOW 90.png': require('../../assets/images/upvc/UPVC- REDUCING ELBOW 90.png'),
  '/images/upvc/UPVC- REDUCING TEE.png': require('../../assets/images/upvc/UPVC- REDUCING TEE.png'),
  '/images/upvc/UPVC- SCH-40 PIPE.png': require('../../assets/images/upvc/UPVC- SCH-40 PIPE.png'),
  '/images/upvc/UPVC- SCH-80 PIPE.png': require('../../assets/images/upvc/UPVC- SCH-80 PIPE.png'),
  '/images/upvc/UPVC- SCH-80 THREADED PIPE.png': require('../../assets/images/upvc/UPVC- SCH-80 THREADED PIPE.png'),
  '/images/upvc/UPVC- STEP OVER BEND.png': require('../../assets/images/upvc/UPVC- STEP OVER BEND.png'),
  '/images/upvc/UPVC- TANK NIPPLE (SOCKETED).png': require('../../assets/images/upvc/UPVC- TANK NIPPLE (SOCKETED).png'),
  '/images/upvc/UPVC- TANK NIPPLE (THREADED).png': require('../../assets/images/upvc/UPVC- TANK NIPPLE (THREADED).png'),
  '/images/upvc/UPVC- TEE.png': require('../../assets/images/upvc/UPVC- TEE.png'),
  '/images/upvc/UPVC- THREADED ELBOW 90.png': require('../../assets/images/upvc/UPVC- THREADED ELBOW 90.png'),
  '/images/upvc/UPVC- UNION BALL VALVE (LONG HANDLE).png': require('../../assets/images/upvc/UPVC- UNION BALL VALVE (LONG HANDLE).png'),
  '/images/upvc/UPVC- UNION BALL VALVE (SHORT HANDLE).png': require('../../assets/images/upvc/UPVC- UNION BALL VALVE (SHORT HANDLE).png'),
  '/images/upvc/UPVC- UNION.png': require('../../assets/images/upvc/UPVC- UNION.png'),
};
